var fccs = require('./fccs.js');

var str = '<li class="item salelist"ref="http://second.jx.fccs.com/sale/72015208.html"><div class="pic"><table><tbody><tr><td><a href="http://second.jx.fccs.com/sale/72015208.html"target="_blank"><img class="resizeleft"width="160"height="120"src=" http://imgf1.fccs.com.cn/public/img/no-photo-new_m160x120.jpg&#10;"></a></td></tr></tbody></table></div><div class="info0"><div class="t"><label for=""><a href="http://second.jx.fccs.com/sale/72015208.html"target="_blank">花园æneocomplcache_start_auto_complete)´房满2年下沉房东诚心卖看房方便</a></label><img src="http://imgf1.fccs.com.cn/second/public/v1/images/s1.gif"alt=""class="vm"></div><div class="lp"><label for=""class="f14 fb"><a href="http://second.jx.fccs.com/sale/72015208.html"target="_blank"class="w_l_2">鑫控·吴越学府</a></label><label for="">[南湖新区-]南湖区由拳路与亚欧路交汇处</label></div><div class="s"><label for="">复式&amp;叠加|<span class="w_c_1">6室3厅3卫</span>|-1/6层|毛坯|朝南</label></div><div class="s1"><div class="n fl pt5 pr10"><label for="">开(neocomplcache_start_auto_complete) 云鹏</label><img src="http://imgf1.fccs.com.cn/public/img/broker/level_4.gif"alt="4"class="vm"><!--<img src="http://imgf1.fccs.com.cn/second/public/v1/images/level_4.gif"alt=""class="vm"/>--><label for=""class="w_c_5">10-26更新</label></div><div class="fl tag">知名学校</div><div class="fl tag">满2年</div><div class="cb0"></div></div></div><div style="height:20px;"><div class="info1"><div class="p1"><div class="fl">256m²</div><div class="fr w_c_1 fb"><span class="f24 arial">300</span>万</div></div><div class="p2 tr">约11719元/m²</div></div></div><div class="cb0"></div></li>';

var paging = '<div class="fr pages-nav"><span class="next">«上一页</span> <span class="current">1</span> <a class="page" href="/sale/search/fr1_ai1-6_p2.html">2</a> <a class="page" href="/sale/search/fr1_ai1-6_p3.html">3</a> <a class="page" href="/sale/search/fr1_ai1-6_p4.html">4</a> <a class="page" href="/sale/search/fr1_ai1-6_p5.html">5</a> <a class="page" href="/sale/search/fr1_ai1-6_p6.html">6</a> <a class="page" href="/sale/search/fr1_ai1-6_p7.html">7</a> <a class="page" href="/sale/search/fr1_ai1-6_p8.html">8</a> <span>…</span> <a class="page" href="/sale/search/fr1_ai1-6_p5331.html">5331</a> <a class="page" href="/sale/search/fr1_ai1-6_p2.html">下一页»</a><div style="clear:both"></div></div>';

var f = new fccs();
var s = f.getPage(paging);
console.log(s);
